// <auto-generated />
namespace SMS.Migrations.SMSmigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserStatus_datatype_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserStatus_datatype_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201807071934299_UserStatus_datatype_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
